DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS refunds;
DROP TABLE IF EXISTS webhook_events;
DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS payment_attempts;
DROP TABLE IF EXISTS payment_methods;
DROP TABLE IF EXISTS payment_intents;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS merchants;
